name: sus
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - ipykernel
  - jupyter
  - python=3.11
  - seaborn
  - conda-forge::xmltodict
  - conda-forge::catboost
  - tslearn
  - pip:
    - fmiopendata==0.4.3
    - lets-plot==4.2.0
    - skimpy==0.0.14
