name: sus
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - ipykernel
  - jupyter
  - python=3.11
  - seaborn
  - conda-forge::xmltodict
  - conda-forge::catboost
  - pip:
    - fmiopendata==0.4.3
